# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTUI_RS.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(964, 605)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(-1, 9, 960, 540))
        self.stackedWidget.setStyleSheet("image: url(:/Background_image/BGR-02.jpg);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.Bgr_Page_1 = QtWidgets.QLabel(self.page_1)
        self.Bgr_Page_1.setGeometry(QtCore.QRect(0, 0, 960, 540))
        self.Bgr_Page_1.setAutoFillBackground(False)
        self.Bgr_Page_1.setStyleSheet("image: url(:/Background_image/BGR-1-01.jpg);")
        self.Bgr_Page_1.setText("")
        self.Bgr_Page_1.setObjectName("Bgr_Page_1")
        self.Button_start = QtWidgets.QPushButton(self.page_1)
        self.Button_start.setGeometry(QtCore.QRect(80, 390, 291, 81))
        self.Button_start.setMouseTracking(False)
        self.Button_start.setTabletTracking(False)
        self.Button_start.setAcceptDrops(False)
        self.Button_start.setAutoFillBackground(False)
        self.Button_start.setStyleSheet("")
        self.Button_start.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Source/PAGE 1/PAGE-1-BUTTON-17.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_start.setIcon(icon)
        self.Button_start.setIconSize(QtCore.QSize(294, 76))
        self.Button_start.setCheckable(False)
        self.Button_start.setAutoRepeat(False)
        self.Button_start.setAutoExclusive(False)
        self.Button_start.setAutoDefault(False)
        self.Button_start.setDefault(False)
        self.Button_start.setFlat(True)
        self.Button_start.setObjectName("Button_start")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.back_button = QtWidgets.QPushButton(self.page_2)
        self.back_button.setGeometry(QtCore.QRect(10, 460, 42, 63))
        self.back_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Background_image/PAGE-1-BUTTON-19.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_button.setIcon(icon1)
        self.back_button.setIconSize(QtCore.QSize(42, 63))
        self.back_button.setFlat(True)
        self.back_button.setObjectName("back_button")
        self.history_button = QtWidgets.QPushButton(self.page_2)
        self.history_button.setGeometry(QtCore.QRect(320, 430, 314, 75))
        self.history_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Source/PAGE 2/PAGE-2-BUTTON-18.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.history_button.setIcon(icon2)
        self.history_button.setIconSize(QtCore.QSize(314, 75))
        self.history_button.setFlat(True)
        self.history_button.setObjectName("history_button")
        self.Play_button = QtWidgets.QPushButton(self.page_2)
        self.Play_button.setGeometry(QtCore.QRect(320, 350, 314, 75))
        self.Play_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Source/PAGE 2/PAGE-2-BUTTON-17.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Play_button.setIcon(icon3)
        self.Play_button.setIconSize(QtCore.QSize(314, 75))
        self.Play_button.setFlat(True)
        self.Play_button.setObjectName("Play_button")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 964, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
import Qrc_source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
